# jdbc 配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hpan?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hpan
    password: xxxxx
    # maxLifetime
    hikari:
      max-lifetime: 1800
server:
  port: 2560
  servlet:
    context-path: /
